
name: CI
run-name: Continuous Integration Versioning
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  if_merged:
    runs-on: windows-latest
    if: github.event.pull_request.merged == true
    Apply-SemVer-Tag:
      steps:
        - uses: actions/checkout@v4

        - name: Banksy
          continue-on-error: true
          shell: pwsh
          run: |
            $nextVersion = .\version_chanter.ps1 ${{ github.sha }}

            echo Taggin complete
