
name: CI
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Banksy
        shell: pwsh
        run: |
          $nextVersion = .\version_chanter.ps1 ${{ github.sha }}

          echo Taggin complete
