
name: CI
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Banksy
        continue-on-error: true
        shell: pwsh
        run: |
          echo "Targetting commit id: ${{ github.sha }}"
          echo "Ensuring id exists..."
          git show ${{ github.sha }} --pretty=format:"%H"
          echo "confirmed."
          echo "latest merge id :"
          git log -1 --merges --pretty=format:"%h"
          
          $nextVersion = .\version_chanter.ps1 ${{ github.sha }}

          echo Taggin complete
