
name: CI
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Banksy
        shell: pwsh
        run: |
          .\version_changer.ps1

      - name: Run a multi-line script
        run: |
          echo Taggin complete
