
name: CI
run-name: Continuous Integration Versioning
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  Apply-SemVer-Tag:
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Banksy
        continue-on-error: true
        shell: pwsh
        run: |
          $nextVersion = .\version_chanter.ps1 ${{ github.sha }}

          echo Taggin complete
