
name: CI
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Run version_chanter.ps1 powershell script
      - name: Banksy
        shell: pwsh
        run: |
          .\version_changer.ps1

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Taggin complete
